# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 16:33
from __future__ import unicode_literals

from django.db import migrations
import gradient_colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodel',
            name='color',
        ),
        migrations.AddField(
            model_name='appmodel',
            name='footer_background',
            field=gradient_colorfield.fields.GradientColorField(default='linear-gradient(to bottom, #00f260 0%, #0575e6 100%)', max_length=100, verbose_name='Footer Background'),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='header_background',
            field=gradient_colorfield.fields.GradientColorField(default='linear-gradient(to bottom, #00f260 0%, #0575e6 100%)', max_length=100, verbose_name='Header Background'),
        ),
    ]
